apiVersion: v1
kind: Service
metadata:
    name: j-demo-service
    namespace: demo
    labels:
        app: j-demo
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
    selector:
        app: j-demo
